module.exports.coolUsers = [
    "Bismark",
    "Sazz",
    "Jaspion",
    "Lily",
    "SLEGHART",
    "Lipe",
    "DoguinhoHart",
    "telecom",
    "Orbot",
    "Lord",
    "Orcadius",
    "dollyinhomlg",
    "Livwu",
    "Sunglasses",
    "samodium",
    "CIA",
    "Felipz (baiano)", 
    "Rangeel",
    "xMarcelo",
    "Sate",
    "p4l",
    "Shiny_Gen",
    "Noob.",
    "Mask",
    "Gianblox",
    "Derik",
    "Math",
    "Calango",
    "ph",
    "Otavio",
    "Gina",
    "lu",
    "Felipe",
    "Mango"
    //obs nao sou cooluser mas quero colocar o membro comum de cooluser mas nao consigo faz isso ap mim sazz ;(
]
